version: "3.7"

services:
  node_db:
    image: postgres:15.2
    ports:
      - "5432:5432"
    environment:
      - PG_DB=mbdh
      - PG_USER=postgres
      - PG_PASS=password
      - PG_HOST=172.27.80.1
    volumes:
      - ./psql_data:/var/lib/postgresql/data
    networks:
      - db_net

networks:
  db_net:
    driver: bridge
    name: common_net