version: "2"
services:
  mbdh_db:
    container_name: mbdh_db
    image: postgres:15.2
    environment:
      POSTGRES_DB: mbdh
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      
    volumes:
      - C:\Users\Public\DIP\mqtt_brocker_data_handling\db:/var/lib/postgresql/data1
    ports:
      - "3130:5432"
    networks:
      - db_net_1

    # ports:
    #   - "15430:5432"

networks:
  db_net_1:
    driver: bridge
    name: mbdh_net