version: "3.9"

services:
  node_mbdh_app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PG_DB=mbdh
      - PG_USER=postgres
      - PG_PASS=password
      - PG_HOST=mbdh_db
    volumes:
      - C:\Users\Public\DIP\mqtt_brocker_data_handling\api:/usr/src/app
    networks:
      - mbdh_appnet

networks:
  mbdh_appnet:
    name: mbdh_net
    external: true